[build]
target = "index.html"
release = true
dist = "dist"
public_url = "/"
filehash = false
inject_scripts = true

[watch]
watch = []
ignore = []

[serve]
addresses = ["127.0.0.1"]
port = 3000
open = false
